// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PongAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef PONGAPIFC_H
#define PONGAPIFC_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "PongAPIfc.h"
#include "protocols/TokenEventProtocol.h"

namespace pingPongDff {
namespace pingPong {
namespace pong {

class PongAPIfc {

public:

    virtual void sendTokenEventToToken(const TokenEventProtocol& message) = 0;


    /**
     * Destructor.
     */
    virtual ~PongAPIfc(void) {
        // Nothing to do.
    }

};

} // namespace pong
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::pong::PongAPIfc;
#endif // #ifndef PONGAPIFC_H
