// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PongAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef PONGAP_H
#define PONGAP_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/ActivePartAbs.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeProtocolIdentifiers.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "PongAPHandler.h"
#include "PongAPIfc.h"
//#include "PingPongDff/ProtocolIdentifier.h"
#include "ProtocolIdentifier.h"
#include "protocols/TokenEventProtocol.h"

namespace pingPongDff {
namespace pingPong {
namespace pong {

class PongAP : public ActivePartAbs, public PongAPIfc {

public:
    PortOutput PortOutToken;

    /**
     * Default Constructor.
     */
    PongAP(void);

    /**
     * Destructor.
     */
    virtual ~PongAP(void);

    /**
     * Process a message, run to completion.
     * @see ExecutableIfc::execute
     *
     * Supported protocols:
     *     TokenEventProtocol
     */
    virtual void execute(const uint16_t protocolIdentifier, Deserializer& deserializer);
    virtual void sendTokenEventToToken(const TokenEventProtocol& message);

protected:

    /**
     * see ActivePartAbs.
     */
    virtual void onInitialize(void);

    /**
     * See ActivePartAbs.
     */
    virtual void onStart(void);

private:

    /**
     * Copy Constructor.
     */
    PongAP(const PongAP& other);

    /**
     * Assignment operator.
     */
    PongAP& operator=(const PongAP& other);

    /**
     * ActivePart handler.
     */
    PongAPHandler m_handler;
};

} // namespace pong
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::pong::PongAP;
#endif // #ifndef PONGAP_H
