// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PongAP.dff

// This file was initially generated but can be manually modified.

#include "PongAPHandler.h"

// Constructor.
PongAPHandler::PongAPHandler(PongAPIfc& sender) :
    m_sender(sender)
{
    // Nothing to do.
}

// Destructor.
PongAPHandler::~PongAPHandler(void) {
    // Nothing to do.
} //lint !e1762 may change state of handler, must not be const

// See ActivePartAbs.
void PongAPHandler::onInitialize(void) {
    // Nothing to do.
} //lint !e1762 may change state of handler, must not be const

// See ActivePartAbs.
void PongAPHandler::onStart(void) {
    // Nothing to do.
} //lint !e1762 may change state of handler, must not be const

// Generated TokenEvent protocol handler.
void PongAPHandler::handleTokenEvent(const TokenEventProtocol& message) {
    // TODO implement this Method
    const uint32_t TokenCount = message.getTokenCounter();
	TokenEventProtocol messageOut; 
	messageOut.setTokenCounter(TokenCount + 1U);
	m_sender.sendTokenEventToToken(messageOut);
} //lint !e1762 may change state of handler, must not be const
