// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PongAP.dff

// This file was initially generated but can be manually modified.

#ifndef PONGAPHANDLER_H
#define PONGAPHANDLER_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "PongAPIfc.h"
#include "protocols/TokenEventProtocol.h"

// Diagnostics.h must be last include.
#include <Imt.Base.Core.Diagnostics/Diagnostics.h>

namespace pingPongDff {
namespace pingPong {
namespace pong {

class PongAPHandler {

public:

    /**
     * Constructor.
     */
    explicit PongAPHandler(PongAPIfc& sender);

    /**
     * Destructor.
     */
    virtual ~PongAPHandler(void);

    /**
     * See ActivePartAbs.
     */
    void onInitialize(void);

    /**
     * See ActivePartAbs.
     */
    void onStart(void);

    /**
     * Generated TokenEvent protocol handler.
     */
    void handleTokenEvent(const TokenEventProtocol& message);

private:

    /**
     * Default Constructor.
     */
    explicit PongAPHandler(void); //lint -esym(1526, *PongAPHandler*) // not implemented by purpose

    /**
     * Copy Constructor.
     */
    PongAPHandler(const PongAPHandler& other);

    /**
     * Assignment operator.
     */
    PongAPHandler& operator=(const PongAPHandler& other);

    // Sender interface
    PongAPIfc& m_sender;
};

} // namespace pong
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::pong::PongAPHandler;
#endif // #ifndef PONGAPHANDLER_H
