// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PingPongAPC.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#include "PingPongAPC.h"

// Default Constructor.
PingPongAPC::PingPongAPC(void) :
    ActivePartContainerAbs(),
    Ping(),
    Pong(),
    LedHeartbeat(),
    ButtonIrqHandler(ButtonIrqHandlerIrqAP::Instance),
    ChanButtonIrqHandlerButtonPressToLedHeartbeatPortIn(),
    ChanPongTokenToPingPortIn(),
    ChanPingTokenToPongPortIn()
{
    // Nothing to do.
}

// Destructor.
PingPongAPC::~PingPongAPC(void) {
    // Nothing to do.
}

// see ActivePartContainerAbs.
void PingPongAPC::onInitialize(void) {
    // Initialize included ActiveParts.
    Ping.initialize();
    Pong.initialize();
    LedHeartbeat.initialize();
    ButtonIrqHandler.initialize();
    // Connect Ports.
    ChanButtonIrqHandlerButtonPressToLedHeartbeatPortIn.connectPorts(ButtonIrqHandler.PortOutButtonPress, LedHeartbeat.PortIn);
    ChanPongTokenToPingPortIn.connectPorts(Pong.PortOutToken, Ping.PortIn);
    ChanPingTokenToPongPortIn.connectPorts(Ping.PortOutToken, Pong.PortIn);
}

// see ActivePartContainerAbs.
void PingPongAPC::onStart(void) {
    // Start included ActiveParts.
    Ping.start();
    Pong.start();
    LedHeartbeat.start();
    ButtonIrqHandler.start();
}
