// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from ButtonPressEventProtocol.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts.Test/EventArgsSerializer.h>

// Class under test.
#include "protocols/ButtonPressEventProtocol.h"

// Diagnostics.h must be last include.
#include <Imt.Base.Core.Diagnostics/Diagnostics.h>

using namespace System;
using namespace System::Text;
using namespace System::Collections::Generic;
using namespace Microsoft::VisualStudio::TestTools::UnitTesting;

namespace unitTestPingPongDff {

constexpr bool defaultIsButtonPressed{ false };

constexpr bool expectedIsButtonPressed{ true };

/**
 * Tests the ButtonPressEventProtocol.
 */
[TestClass]
public ref class TestButtonPressEventProtocol {

public:

    [TestInitialize()]
    void setUp() {
        m_pTestMessage = new ButtonPressEventProtocol();
        m_pTestMessage->setIsButtonPressed(expectedIsButtonPressed);
    }

    [TestCleanup()]
    void tearDown() {
        delete m_pTestMessage;
        m_pTestMessage = NULL;
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("The value of MAX_SERIALIZED_SIZE_BYTES is correct")]
    void testButtonPressEventProtocol_maxSerializedSize() {
        // Arrange
        ButtonPressEventProtocol message(*m_pTestMessage);
        constexpr size_t bufferSize = sizeof(ButtonPressEventProtocol);
        uint8_t buffer[bufferSize];
        // Act
        Serializer serializer(buffer, bufferSize);
        message.serialize(serializer);
        // Assert
        Assert::AreEqual(message.MAX_SERIALIZED_SIZE_BYTES, serializer.getBufferPos());
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("All fields are initialized to the correct default value")]
    void testButtonPressEventProtocol_defaultConstructor() {
        // Act
        ButtonPressEventProtocol message;
        // Assert
        assertIsDefault(message);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("All fields are initialized to the given value")]
    void testButtonPressEventProtocol_customConstructor() {
        // Act
        ButtonPressEventProtocol message(
            expectedIsButtonPressed);

        // Assert
        assertIsAsExpected(message);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("All fields are initialized to the correct value from the input message")]
    void testButtonPressEventProtocol_copyConstructor() {
        // Act
        ButtonPressEventProtocol message(*m_pTestMessage);
        // Assert
        assertIsAsExpected(message);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("All fields are set to the correct value from the input message")]
    void testButtonPressEventProtocol_assignmentOperator() {
        // Arrange
        ButtonPressEventProtocol message;
        // Act
        assertIsDefault(message);
        message = *m_pTestMessage;
        // Assert
        assertIsAsExpected(message);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("All fields are set to the correct value from the input message")]
    void testButtonPressEventProtocol_assignmentOperator_assignSelf() {
        // Arrange
        ButtonPressEventProtocol message(*m_pTestMessage);
        // Act
        message = message;
        // Assert
        assertIsAsExpected(message);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("The compare operators == and != works as expected")]
    void testButtonPressEventProtocol_compareOperators() {
        // Arrange
        ButtonPressEventProtocol message(*m_pTestMessage);
        ButtonPressEventProtocol messageEqual(*m_pTestMessage);

        ButtonPressEventProtocol messageDiff1(*m_pTestMessage);
        messageDiff1.setIsButtonPressed(defaultIsButtonPressed);

        // Act / assert
        // equality
        Assert::IsTrue(message == message);
        Assert::IsTrue(message == messageEqual);
        Assert::IsTrue(messageEqual == message);
        Assert::IsFalse(message == messageDiff1);
        // inequality
        Assert::IsFalse(message != message);
        Assert::IsFalse(message != messageEqual);
        Assert::IsFalse(messageEqual != message);
        Assert::IsTrue(message != messageDiff1);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("When serializing and deserializing the message remains the same")]
    void testButtonPressEventProtocol_serialize_deserialize() {
        // Arrange
        ButtonPressEventProtocol inputMessage(*m_pTestMessage);
        constexpr size_t bufferSize = sizeof(ButtonPressEventProtocol);
        uint8_t buffer[bufferSize];
        // Act
        Serializer serializer(buffer, bufferSize);
        inputMessage.serialize(serializer);
        Deserializer deserializer(buffer, bufferSize);
        ButtonPressEventProtocol deserializedMessage(deserializer);
        // Assert
        assertIsAsExpected(deserializedMessage);
    }

    [TestMethod]
    [TestCategory("Software Unit")]
    [Description("The field 'IsButtonPressed' get and set methods work as expected")]
    void testButtonPressEventProtocol_field_IsButtonPressed() {
        // Arrange
        ButtonPressEventProtocol message1;
        ButtonPressEventProtocol message2;
        bool expected1 = false;
        bool expected2 = true;

        // Act
        message1.setIsButtonPressed(expected1);
        message2.setIsButtonPressed(expected2);

        // Assert
        Assert::AreEqual(expected1, message1.getIsButtonPressed());
        Assert::AreEqual(expected2, message2.getIsButtonPressed());
    }

private:

    void assertIsAsExpected(const ButtonPressEventProtocol& message) {
        // IsButtonPressed
        Assert::AreEqual(expectedIsButtonPressed, message.getIsButtonPressed());
    }

    void assertIsDefault(const ButtonPressEventProtocol& message) {
        // IsButtonPressed
        Assert::AreEqual(defaultIsButtonPressed, message.getIsButtonPressed());
    }

    ButtonPressEventProtocol* m_pTestMessage;
};

} // namespace unitTestPingPongDff
