// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from ButtonIrqHandlerIRQAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef BUTTONIRQHANDLERIRQAPIFC_H
#define BUTTONIRQHANDLERIRQAPIFC_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "ButtonIrqHandlerIrqAPIfc.h"
#include "protocols/ButtonPressEventProtocol.h"

namespace pingPongDff {
namespace pingPong {
namespace buttonIrqHandler {

class ButtonIrqHandlerIrqAPIfc {

public:

    virtual void sendButtonPressEventToButtonPress(const ButtonPressEventProtocol& message) = 0;


    /**
     * Destructor.
     */
    virtual ~ButtonIrqHandlerIrqAPIfc(void) {
        // Nothing to do.
    }

};

} // namespace buttonIrqHandler
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::buttonIrqHandler::ButtonIrqHandlerIrqAPIfc;
#endif // #ifndef BUTTONIRQHANDLERIRQAPIFC_H
