// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from protocolsIdentifiers.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef PROTOCOLIDENTIFIER_H
#define PROTOCOLIDENTIFIER_H

// Imt.Base includes.
#include <Imt.Base.Core.Platform/Platform.h>

namespace pingPongDff {

/**
 * Contains all protocol identifiers of the generated project.
 */
struct ProtocolIdentifier {
    static const uint16_t TOKEN_EVENT        = 1000U;
    static const uint16_t BUTTON_PRESS_EVENT = 1001U;
};

} // namespace pingPongDff
using pingPongDff::ProtocolIdentifier;
#endif // #ifndef PROTOCOLIDENTIFIER_H
