// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from ButtonPressEventProtocol.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef BUTTONPRESSEVENTPROTOCOL_H
#define BUTTONPRESSEVENTPROTOCOL_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Core.Serialization/Deserializer.h>
#include <Imt.Base.Core.Serialization/SerializableIfc.h>
#include <Imt.Base.Core.Serialization/Serializer.h>

// Project includes.
#include "ProtocolIdentifier.h"

namespace pingPongDff {
namespace protocols {

/**
 * Protocol for Button Press Event
 */
class ButtonPressEventProtocol : public SerializableIfc {

public:

    /**
     * Protocol Identifier.
     */
    static const uint16_t IDENTIFIER = ProtocolIdentifier::BUTTON_PRESS_EVENT;

    /**
     * Maximum serialized data bytes.
     */
    static const uint32_t MAX_SERIALIZED_SIZE_BYTES = 1U;

    /**
     * Default Constructor.
     */
    explicit ButtonPressEventProtocol(void);

    /**
     * Custom Constructor.
     */
    explicit ButtonPressEventProtocol(const bool IsButtonPressed);

    /**
     * Copy constructor.
     */
    ButtonPressEventProtocol(const ButtonPressEventProtocol& other);

    /**
     * Constructor from deserializer.
     */
    explicit ButtonPressEventProtocol(Deserializer& deserializer);

    /**
     * Destructor.
     */
    virtual ~ButtonPressEventProtocol(void);

    /**
     * Assignment operator.
     */
    ButtonPressEventProtocol& operator=(const ButtonPressEventProtocol& other);

    /**
     * Equality operator.
     */
    bool operator==(const ButtonPressEventProtocol& right) const;

    /**
     * Inequality operator.
     */
    bool operator!=(const ButtonPressEventProtocol& right) const;

    /**
     * @see SerializableIfc
     */
    //lint -sem(pingPongDff::protocols::ButtonPressEventProtocol::deserialize,initializer) // Members initialized in deserializer function
    virtual void deserialize(Deserializer& deserializer);

    /**
     * @see SerializableIfc
     */
    virtual void serialize(Serializer& serializer) const;

    // Setter for IsButtonPressed
    void setIsButtonPressed(const bool IsButtonPressed);

    // Getter for IsButtonPressed
    bool getIsButtonPressed(void) const;

private:

    // Instance members
    bool m_IsButtonPressed;
};

} // namespace protocols
} // namespace pingPongDff
using pingPongDff::protocols::ButtonPressEventProtocol;
#endif // #ifndef BUTTONPRESSEVENTPROTOCOL_H
