// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from PingAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef PINGAPIFC_H
#define PINGAPIFC_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "PingAPIfc.h"
#include "protocols/TokenEventProtocol.h"
 

namespace pingPongDff {
namespace pingPong {
namespace ping {

class PingAPIfc {

public:

    virtual void sendTokenEventToToken(const TokenEventProtocol& message) = 0;


    /**
     * Destructor.
     */
    virtual ~PingAPIfc(void) {
        // Nothing to do.
    }

};

} // namespace ping
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::ping::PingAPIfc;
#endif // #ifndef PINGAPIFC_H
