// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from LedHeartbeatAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

#ifndef LEDHEARTBEATAPIFC_H
#define LEDHEARTBEATAPIFC_H

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts/PeriodicTimer.h>
#include <Imt.Base.Dff.ActiveParts/PortOutput.h>
#include <Imt.Base.Dff.Runtime/RuntimeTimerEvent.h>

// Project includes.
#include "LedHeartbeatAPIfc.h"
#include "protocols/ButtonPressEventProtocol.h"

namespace pingPongDff {
namespace pingPong {
namespace ledHeartbeat {

class LedHeartbeatAPIfc {

public:

    virtual PeriodicTimer& getHeartBeatTimerTimer(void) = 0;


    /**
     * Destructor.
     */
    virtual ~LedHeartbeatAPIfc(void) {
        // Nothing to do.
    }

};

} // namespace ledHeartbeat
} // namespace pingPong
} // namespace pingPongDff
using pingPongDff::pingPong::ledHeartbeat::LedHeartbeatAPIfc;
#endif // #ifndef LEDHEARTBEATAPIFC_H
