// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.6
//
// Generated by DffGenerator (Version 1.00.0)
// Generated from LedHeartbeatAP.dff

// AUTO-GENERATED FILE. DO NOT MODIFY.

// Imt.Base includes.
// Platform.h must be very first include.
#include <Imt.Base.Core.Platform/Platform.h>
#include <Imt.Base.Dff.ActiveParts.Test/ChannelMockIn.h>
#include <Imt.Base.Dff.ActiveParts.Test/ChannelMockOut.h>
#include <Imt.Base.Dff.ActiveParts.Test/ChannelConnectionVerifier.h>

// Helper includes.
#include "Helpers/ActivePartHelper.h"
#include "Helpers/MockTestBase.h"

// Class under test.
#include "PingPong/LedHeartbeat/LedHeartbeatAP.h"

// Diagnostics.h must be last include.
#include <Imt.Base.Core.Diagnostics/Diagnostics.h>

using namespace System;
using namespace System::Text;
using namespace System::Collections::Generic;
using namespace Microsoft::VisualStudio::TestTools::UnitTesting;

namespace unitTestPingPongDff {

/**
 * Tests the LedHeartbeatAP.
 */
[TestClass]
public ref class TestLedHeartbeatAP : MockTestBase {

public:

    [TestInitialize()]
    void setUp() {
        m_pTestObject = new LedHeartbeatAP();
        m_pChannelIn = new ChannelMockIn();
        // Initialize.
        m_pTestObject->initialize();
        // Connect ports.
        m_pChannelIn->connectPortIn(m_pTestObject->PortIn);
        // Start.
        m_pTestObject->start();
    }

    [TestCleanup()]
    void tearDown() {
        delete m_pChannelIn;
        m_pChannelIn = NULL;
        delete m_pTestObject;
        m_pTestObject = NULL;
    }

    [TestMethod]
    [TestCategory("Software UNIT")]
    [Description("Runtime Priority as specified.")]
    void testLedHeartbeatAP_Priority() {
        Assert::IsTrue(RuntimePriority::Prio_16 == m_pTestObject->getPriority());
    }

private:

    LedHeartbeatAP* m_pTestObject;
    ChannelMockIn* m_pChannelIn;
};

} // namespace unitTestPingPongDff
